export const ERROR_CODES = {
  INVALID_OTP: "INVALID_OTP",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  MOBILE_REQUIRED: "MOBILE_REQUIRED",
  UNAUTHORIZED: "UNAUTHORIZED",
  SERVER_ERROR: "SERVER_ERROR",
};